# This workflow will build and deploy a .NET project to AWS Elastic Beanstalk
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy-Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Replace placeholders in appsettings.json
      run: |
        sed -i 's/{DB_SERVER}/'${{ secrets.DB_SERVER }}'/' appsettings.json
        sed -i 's/{DB_DATABASE}/'${{ secrets.DB_DATABASE }}'/' appsettings.json
        sed -i 's/{DB_USER}/'${{ secrets.DB_USER }}'/' appsettings.json
        sed -i 's/{DB_PASSWORD}/'${{ secrets.DB_PASSWORD }}'/' appsettings.json

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Compress deployment package
      run: zip -r deploy.zip ./publish

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name my-app \
          --version-label ${{ github.sha }} \
          --source-bundle S3Bucket="my-bucket",S3Key="deploy.zip"

        aws elasticbeanstalk update-environment \
          --application-name my-app \
          --environment-name my-env \
          --version-label ${{ github.sha }}
